# Generated by Django 5.2.7 on 2026-09-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurseprofile',
            name='license_extracted',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='license_file',
            field=models.FileField(blank=True, null=True, upload_to='nurse_licenses/'),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='license_review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='license_status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='registration_type',
            field=models.CharField(choices=[('PIN', 'NMC PIN (Nurse)'), ('AIN', 'AIN (Midwife)')], default='PIN', max_length=20),
        ),
    ]
