# Generated by Django 5.2.7 on 2026-09-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_alter_nurseprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedHospitalDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('hospital', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='nurseprofile',
            name='license_extracted',
        ),
        migrations.RemoveField(
            model_name='nurseprofile',
            name='license_file',
        ),
        migrations.RemoveField(
            model_name='nurseprofile',
            name='license_review_note',
        ),
        migrations.RemoveField(
            model_name='nurseprofile',
            name='license_status',
        ),
    ]
