# Generated by Django 5.2.7 on 2026-10-07 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0007_seed_300_hospitals_and_domains'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinic',
            options={'ordering': ['name']},
        ),
    ]
